# Generated by Django 2.2.12 on 2023-04-22 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsInPackage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('shipment_id', models.IntegerField(null=True)),
                ('product_id', models.IntegerField(null=True)),
                ('product_description', models.CharField(max_length=200, null=True)),
                ('product_quantity', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shipments',
            fields=[
                ('shipment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('truck_id', models.IntegerField(null=True)),
                ('wh_x', models.IntegerField(null=True)),
                ('wh_y', models.IntegerField(null=True)),
                ('dest_x', models.IntegerField(null=True)),
                ('dest_y', models.IntegerField(null=True)),
                ('shipment_status', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('truck_id', models.IntegerField(primary_key=True, serialize=False)),
                ('truck_x', models.IntegerField(null=True)),
                ('truck_y', models.IntegerField(null=True)),
                ('truck_status', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
