# Generated by Django 4.2 on 2023-04-25 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipments',
            fields=[
                ('shipment_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('ups_userid', models.IntegerField(null=True)),
                ('truck_id', models.IntegerField()),
                ('wh_id', models.IntegerField()),
                ('dest_x', models.IntegerField()),
                ('dest_y', models.IntegerField()),
                ('shipment_status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('truck_id', models.IntegerField(primary_key=True, serialize=False)),
                ('truck_x', models.IntegerField()),
                ('truck_y', models.IntegerField()),
                ('truck_status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProductsInPackage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.IntegerField(null=True)),
                ('product_description', models.CharField(max_length=200, null=True)),
                ('product_quantity', models.IntegerField(null=True)),
                ('shipment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ups_website.shipments')),
            ],
        ),
    ]
