# Generated by Django 4.2 on 2023-04-29 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ups_website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('amazon_id', models.IntegerField(null=True)),
                ('user_name', models.CharField(max_length=200)),
                ('user_email', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='truck',
            name='wh_id',
            field=models.IntegerField(null=True),
        ),
    ]
