# Generated by Django 2.2.12 on 2023-04-22 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ups_website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsinpackage',
            name='shipment_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shipments',
            name='shipment_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
