# Generated by Django 2.2.12 on 2023-04-22 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ups_website', '0002_auto_20230422_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsinpackage',
            name='shipment_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='shipments',
            name='shipment_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
